# Site settings
title: Leon Paternoster
email: leon.paternoster@unseen.is
description: > # this means to ignore newlines until "baseurl:"
  I'm Leon, a web manager. I blog about working on the web and other, unrelated things, such as politics, books and football.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://leonpaternoster.com" # the base hostname & protocol for your site
twitter_username: leonpaternoster
github_username:  leonp

# Build settings
markdown: kramdown
