# Site settings
title: Leon Paternoster
email: leon.paternoster@zoho.com
description: Digital and customer service manager at Suffolk Libraries. Design, coding, strategy and project management.
biog: 'I&#8217;m digital and customer service manager at Suffolk Libraries. I&#8217;ve been writing about design, code and managing websites since 2008, and you&#8217;ll find a hundred or so articles on this site. Email <em>leon.paternoster@zoho.com</em>, <a href="https://twitter.com/leonpaternoster" class="dark-blue hover-dark-red bb b--dotted bl-0 br-0 bt-0">Tweet me</a> or <a href="https://uk.linkedin.com/in/leonpaternoster" class="dark-blue hover-dark-red bb b--dotted bl-0 br-0 bt-0">contact me on LinkedIn</a>'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.leonpaternoster.com" # the base hostname & protocol for your site
twitter_username: leonpaternoster
github_username:  leonp

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
sass:
  style: compressed

# Enable is.post test for posts
# Means we don't need a post layout
# But we can test for a post in layouts/default.html
# Simply use {% if page.is_post %}

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
      layout: default
