# Site settings
title: Leon Paternoster
email: leon.paternoster@zoho.com
description: Web and customer service manager at Suffolk Libraries. Blogs about working on the web, libraries and politics. ℓƥ
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.leonpaternoster.com" # the base hostname & protocol for your site
twitter_username: leonpaternoster
github_username:  leonp

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
sass:
  style: compressed
